substitutions:
  name: jarcik_module
  pass: 'aaa'
  ssid: 'bbb'
  ssid_pass: 'ccc'
  
esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: ${ssid}
  password: ${ssid_pass}

web_server:
  port: 80

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ${pass}
  
ota:
  password: ${pass}

binary_sensor:
- platform: gpio
  pin:
    number: GPIO14
    inverted: true
  id: up
  name: up
  on_state:
    then:
      - lambda: |
          if (id(my_cover).current_operation == COVER_OPERATION_IDLE) {
            // Cover is idle, check current state and either open or close cover.
           id(my_cover).open();
          } else {
            id(my_cover).stop();
          }
- platform: gpio
  pin:
    number: GPIO16
    inverted: true    
  id: down
  name: down
  on_state:
    then:
      - lambda: |
          if (id(my_cover).current_operation == COVER_OPERATION_IDLE) {
           id(my_cover).close();
          } else {
          id(my_cover).stop();
          }
          
switch:
- platform: gpio
  pin: GPIO12
  interlock: &interlock [open_cover, close_cover]
  id: open_cover
- platform: gpio
  pin: GPIO13
  interlock: *interlock
  id: close_cover

cover:
- platform: time_based
  name: "Cover"
  id: my_cover
  open_action:
    - switch.turn_on: open_cover
  open_duration: 60s
  close_action:
    - switch.turn_on: close_cover
  close_duration: 60s
  stop_action:
    - switch.turn_off: open_cover
    - switch.turn_off: close_cover

sensor:  
  - platform: uptime
    name: ${name}_Uptime
    icon: mdi:clock-outline
    update_interval: 300s
    unit_of_measurement: days
    filters:
      - multiply: 0.000011574
    
  - platform: wifi_signal
    name: "${name}_wifi_Signal"
    update_interval: 300s    

  - platform: dallas
    address: 0xF50316A2796BE728
    name: ${name}_Temp
    
dallas:
  - pin: GPIO2
    update_interval: 10s
    
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${name}_Adress_IP
    ssid:
      name: ${name}_SSID    
    bssid:
      name: ${name}_BSSID

  - platform: version
    name: "${name}_ESPHome_Version"        